import type { AppLanguage } from './index'

type SharedMessages = Record<string, string>

const languageNames: Record<AppLanguage, SharedMessages> = {
  es: { 'nav.pymes': 'Pymes', 'nav.learning': 'Aprendizaje', 'nav.tools': 'Herramientas', 'nav.dashboard': 'Dashboard', 'nav.blog': 'Blog', 'nav.settings': 'Opciones', 'nav.profile': 'Ir a mi perfil', 'nav.language': 'Idioma', 'settings.title': 'Opciones', 'settings.description': 'Personaliza cómo se muestra Mentras en todos tus dispositivos.', 'settings.languageDetail': 'Define el idioma de navegación y de las pantallas compartidas.', 'settings.appearance': 'Apariencia', 'settings.appearanceDetail': 'El tema seleccionado se aplica a toda la web.', 'theme.light': 'Modo claro', 'theme.dark': 'Modo oscuro', 'footer.explore': 'Explorar', 'footer.resources': 'Recursos', 'footer.legal': 'Legal', 'footer.home': 'Inicio', 'footer.contact': 'Contacto', 'footer.privacy': 'Privacidad', 'footer.terms': 'Terminos' },
  en: { 'nav.pymes': 'Businesses', 'nav.learning': 'Learning', 'nav.tools': 'Tools', 'nav.dashboard': 'Dashboard', 'nav.blog': 'Blog', 'nav.settings': 'Settings', 'nav.profile': 'My profile', 'nav.language': 'Language', 'settings.title': 'Settings', 'settings.description': 'Customize how Mentras is displayed across the entire website.', 'settings.languageDetail': 'Set the language used in navigation and shared screens.', 'settings.appearance': 'Appearance', 'settings.appearanceDetail': 'Your selected theme applies across the entire website.', 'theme.light': 'Light mode', 'theme.dark': 'Dark mode', 'footer.explore': 'Explore', 'footer.resources': 'Resources', 'footer.legal': 'Legal', 'footer.home': 'Home', 'footer.contact': 'Contact', 'footer.privacy': 'Privacy', 'footer.terms': 'Terms' },
  pt: { 'nav.pymes': 'Empresas', 'nav.learning': 'Aprendizagem', 'nav.tools': 'Ferramentas', 'nav.dashboard': 'Painel', 'nav.blog': 'Blog', 'nav.settings': 'Opções', 'nav.profile': 'Meu perfil', 'nav.language': 'Idioma', 'settings.title': 'Opções', 'settings.description': 'Personalize como o Mentras é exibido em todo o site.', 'settings.languageDetail': 'Defina o idioma usado na navegação e nas telas compartilhadas.', 'settings.appearance': 'Aparência', 'settings.appearanceDetail': 'O tema selecionado é aplicado em todo o site.', 'theme.light': 'Modo claro', 'theme.dark': 'Modo escuro', 'footer.explore': 'Explorar', 'footer.resources': 'Recursos', 'footer.legal': 'Legal', 'footer.home': 'Início', 'footer.contact': 'Contato', 'footer.privacy': 'Privacidade', 'footer.terms': 'Termos' },
  fr: { 'nav.pymes': 'Entreprises', 'nav.learning': 'Apprentissage', 'nav.tools': 'Outils', 'nav.dashboard': 'Tableau de bord', 'nav.blog': 'Blog', 'nav.settings': 'Paramètres', 'nav.profile': 'Mon profil', 'nav.language': 'Langue', 'settings.title': 'Paramètres', 'settings.description': 'Personnalisez l’affichage de Mentras sur l’ensemble du site.', 'settings.languageDetail': 'Définissez la langue utilisée dans la navigation et les écrans partagés.', 'settings.appearance': 'Apparence', 'settings.appearanceDetail': 'Le thème sélectionné s’applique à l’ensemble du site.', 'theme.light': 'Mode clair', 'theme.dark': 'Mode sombre', 'footer.explore': 'Explorer', 'footer.resources': 'Ressources', 'footer.legal': 'Mentions légales', 'footer.home': 'Accueil', 'footer.contact': 'Contact', 'footer.privacy': 'Confidentialité', 'footer.terms': 'Conditions' },
  de: { 'nav.pymes': 'Unternehmen', 'nav.learning': 'Lernen', 'nav.tools': 'Werkzeuge', 'nav.dashboard': 'Dashboard', 'nav.blog': 'Blog', 'nav.settings': 'Einstellungen', 'nav.profile': 'Mein Profil', 'nav.language': 'Sprache', 'settings.title': 'Einstellungen', 'settings.description': 'Passe an, wie Mentras auf der gesamten Website angezeigt wird.', 'settings.languageDetail': 'Lege die Sprache für Navigation und gemeinsame Ansichten fest.', 'settings.appearance': 'Darstellung', 'settings.appearanceDetail': 'Das ausgewählte Design gilt für die gesamte Website.', 'theme.light': 'Heller Modus', 'theme.dark': 'Dunkler Modus', 'footer.explore': 'Entdecken', 'footer.resources': 'Ressourcen', 'footer.legal': 'Rechtliches', 'footer.home': 'Startseite', 'footer.contact': 'Kontakt', 'footer.privacy': 'Datenschutz', 'footer.terms': 'Nutzungsbedingungen' },
  it: { 'nav.pymes': 'Imprese', 'nav.learning': 'Apprendimento', 'nav.tools': 'Strumenti', 'nav.dashboard': 'Dashboard', 'nav.blog': 'Blog', 'nav.settings': 'Impostazioni', 'nav.profile': 'Il mio profilo', 'nav.language': 'Lingua', 'settings.title': 'Impostazioni', 'settings.description': 'Personalizza come Mentras viene visualizzato in tutto il sito.', 'settings.languageDetail': 'Imposta la lingua usata nella navigazione e nelle schermate condivise.', 'settings.appearance': 'Aspetto', 'settings.appearanceDetail': 'Il tema selezionato si applica a tutto il sito.', 'theme.light': 'Modalità chiara', 'theme.dark': 'Modalità scura', 'footer.explore': 'Esplora', 'footer.resources': 'Risorse', 'footer.legal': 'Legale', 'footer.home': 'Home', 'footer.contact': 'Contatti', 'footer.privacy': 'Privacy', 'footer.terms': 'Termini' },
  ru: { 'nav.pymes': 'Компании', 'nav.learning': 'Обучение', 'nav.tools': 'Инструменты', 'nav.dashboard': 'Панель', 'nav.blog': 'Блог', 'nav.settings': 'Настройки', 'nav.profile': 'Мой профиль', 'nav.language': 'Язык', 'settings.title': 'Настройки', 'settings.description': 'Настройте отображение Mentras на всем сайте.', 'settings.languageDetail': 'Выберите язык навигации и общих экранов.', 'settings.appearance': 'Внешний вид', 'settings.appearanceDetail': 'Выбранная тема применяется ко всему сайту.', 'theme.light': 'Светлый режим', 'theme.dark': 'Темный режим', 'footer.explore': 'Обзор', 'footer.resources': 'Ресурсы', 'footer.legal': 'Правовая информация', 'footer.home': 'Главная', 'footer.contact': 'Контакты', 'footer.privacy': 'Конфиденциальность', 'footer.terms': 'Условия' },
  zh: { 'nav.pymes': '企业', 'nav.learning': '学习', 'nav.tools': '工具', 'nav.dashboard': '仪表板', 'nav.blog': '博客', 'nav.settings': '设置', 'nav.profile': '我的资料', 'nav.language': '语言', 'settings.title': '设置', 'settings.description': '自定义 Mentras 在整个网站中的显示方式。', 'settings.languageDetail': '设置导航和共享页面使用的语言。', 'settings.appearance': '外观', 'settings.appearanceDetail': '所选主题会应用到整个网站。', 'theme.light': '浅色模式', 'theme.dark': '深色模式', 'footer.explore': '探索', 'footer.resources': '资源', 'footer.legal': '法律', 'footer.home': '首页', 'footer.contact': '联系', 'footer.privacy': '隐私', 'footer.terms': '条款' },
  ja: { 'nav.pymes': '企業', 'nav.learning': '学習', 'nav.tools': 'ツール', 'nav.dashboard': 'ダッシュボード', 'nav.blog': 'ブログ', 'nav.settings': '設定', 'nav.profile': 'プロフィール', 'nav.language': '言語', 'settings.title': '設定', 'settings.description': 'Mentras の表示方法をサイト全体でカスタマイズします。', 'settings.languageDetail': 'ナビゲーションと共有画面で使う言語を設定します。', 'settings.appearance': '外観', 'settings.appearanceDetail': '選択したテーマはサイト全体に適用されます。', 'theme.light': 'ライトモード', 'theme.dark': 'ダークモード', 'footer.explore': '探索', 'footer.resources': 'リソース', 'footer.legal': '法的情報', 'footer.home': 'ホーム', 'footer.contact': 'お問い合わせ', 'footer.privacy': 'プライバシー', 'footer.terms': '利用規約' },
  ar: { 'nav.pymes': 'الشركات', 'nav.learning': 'التعلم', 'nav.tools': 'الأدوات', 'nav.dashboard': 'لوحة التحكم', 'nav.blog': 'المدونة', 'nav.settings': 'الإعدادات', 'nav.profile': 'ملفي الشخصي', 'nav.language': 'اللغة', 'settings.title': 'الإعدادات', 'settings.description': 'خصّص طريقة عرض Mentras في كل الموقع.', 'settings.languageDetail': 'حدد لغة التنقل والشاشات المشتركة.', 'settings.appearance': 'المظهر', 'settings.appearanceDetail': 'يتم تطبيق النمط المحدد على الموقع بالكامل.', 'theme.light': 'الوضع الفاتح', 'theme.dark': 'الوضع الداكن', 'footer.explore': 'استكشف', 'footer.resources': 'الموارد', 'footer.legal': 'قانوني', 'footer.home': 'الرئيسية', 'footer.contact': 'اتصل بنا', 'footer.privacy': 'الخصوصية', 'footer.terms': 'الشروط' },
  hi: { 'nav.pymes': 'व्यवसाय', 'nav.learning': 'सीखना', 'nav.tools': 'उपकरण', 'nav.dashboard': 'डैशबोर्ड', 'nav.blog': 'ब्लॉग', 'nav.settings': 'सेटिंग्स', 'nav.profile': 'मेरी प्रोफ़ाइल', 'nav.language': 'भाषा', 'settings.title': 'सेटिंग्स', 'settings.description': 'पूरी वेबसाइट पर Mentras कैसे दिखे, इसे अनुकूलित करें।', 'settings.languageDetail': 'नेविगेशन और साझा स्क्रीन में उपयोग की जाने वाली भाषा सेट करें।', 'settings.appearance': 'दिखावट', 'settings.appearanceDetail': 'चुनी गई थीम पूरी वेबसाइट पर लागू होती है।', 'theme.light': 'लाइट मोड', 'theme.dark': 'डार्क मोड', 'footer.explore': 'खोजें', 'footer.resources': 'संसाधन', 'footer.legal': 'कानूनी', 'footer.home': 'होम', 'footer.contact': 'संपर्क', 'footer.privacy': 'गोपनीयता', 'footer.terms': 'शर्तें' },
  nl: { 'nav.pymes': 'Bedrijven', 'nav.learning': 'Leren', 'nav.tools': 'Tools', 'nav.dashboard': 'Dashboard', 'nav.blog': 'Blog', 'nav.settings': 'Instellingen', 'nav.profile': 'Mijn profiel', 'nav.language': 'Taal', 'settings.title': 'Instellingen', 'settings.description': 'Pas aan hoe Mentras op de hele website wordt weergegeven.', 'settings.languageDetail': 'Stel de taal in voor navigatie en gedeelde schermen.', 'settings.appearance': 'Weergave', 'settings.appearanceDetail': 'Het gekozen thema geldt voor de hele website.', 'theme.light': 'Lichte modus', 'theme.dark': 'Donkere modus', 'footer.explore': 'Verkennen', 'footer.resources': 'Hulpmiddelen', 'footer.legal': 'Juridisch', 'footer.home': 'Home', 'footer.contact': 'Contact', 'footer.privacy': 'Privacy', 'footer.terms': 'Voorwaarden' },
}

export default languageNames
