import type { AppLanguage } from './index'

type SharedMessages = Record<string, string>

const languageNames: Record<AppLanguage, SharedMessages> = {
  es: { 'nav.pymes': 'Pymes', 'nav.learning': 'Aprendizaje', 'nav.tools': 'Herramientas', 'nav.dashboard': 'Dashboard', 'nav.blog': 'Blog', 'nav.settings': 'Opciones', 'nav.profile': 'Ir a mi perfil', 'nav.language': 'Idioma', 'settings.title': 'Opciones', 'settings.description': 'Personaliza cómo se muestra Mentras en todos tus dispositivos.', 'settings.languageDetail': 'Define el idioma de navegación y de las pantallas compartidas.', 'settings.appearance': 'Apariencia', 'settings.appearanceDetail': 'El tema seleccionado se aplica a toda la web.', 'theme.light': 'Modo claro', 'theme.dark': 'Modo oscuro', 'footer.explore': 'Explorar', 'footer.resources': 'Recursos', 'footer.legal': 'Legal', 'footer.home': 'Inicio', 'footer.contact': 'Contacto', 'footer.privacy': 'Privacidad', 'footer.terms': 'Terminos' },
  en: { 'nav.pymes': 'Businesses', 'nav.learning': 'Learning', 'nav.tools': 'Tools', 'nav.dashboard': 'Dashboard', 'nav.blog': 'Blog', 'nav.settings': 'Settings', 'nav.profile': 'My profile', 'nav.language': 'Language', 'settings.title': 'Settings', 'settings.description': 'Customize how Mentras is displayed across the entire website.', 'settings.languageDetail': 'Set the language used in navigation and shared screens.', 'settings.appearance': 'Appearance', 'settings.appearanceDetail': 'Your selected theme applies across the entire website.', 'theme.light': 'Light mode', 'theme.dark': 'Dark mode', 'footer.explore': 'Explore', 'footer.resources': 'Resources', 'footer.legal': 'Legal', 'footer.home': 'Home', 'footer.contact': 'Contact', 'footer.privacy': 'Privacy', 'footer.terms': 'Terms' },
  pt: { 'nav.pymes': 'Empresas', 'nav.learning': 'Aprendizagem', 'nav.tools': 'Ferramentas', 'nav.dashboard': 'Painel', 'nav.blog': 'Blog', 'nav.settings': 'Opções', 'nav.profile': 'Meu perfil', 'nav.language': 'Idioma', 'settings.title': 'Opções', 'settings.description': 'Personalize como o Mentras é exibido em todo o site.', 'settings.languageDetail': 'Defina o idioma usado na navegação e nas telas compartilhadas.', 'settings.appearance': 'Aparência', 'settings.appearanceDetail': 'O tema selecionado é aplicado em todo o site.', 'theme.light': 'Modo claro', 'theme.dark': 'Modo escuro', 'footer.explore': 'Explorar', 'footer.resources': 'Recursos', 'footer.legal': 'Legal', 'footer.home': 'Início', 'footer.contact': 'Contato', 'footer.privacy': 'Privacidade', 'footer.terms': 'Termos' },
  fr: { 'nav.pymes': 'Entreprises', 'nav.learning': 'Apprentissage', 'nav.tools': 'Outils', 'nav.dashboard': 'Tableau de bord', 'nav.blog': 'Blog', 'nav.settings': 'Paramètres', 'nav.profile': 'Mon profil', 'nav.language': 'Langue', 'settings.title': 'Paramètres', 'settings.description': 'Personnalisez l’affichage de Mentras sur l’ensemble du site.', 'settings.languageDetail': 'Définissez la langue utilisée dans la navigation et les écrans partagés.', 'settings.appearance': 'Apparence', 'settings.appearanceDetail': 'Le thème sélectionné s’applique à l’ensemble du site.', 'theme.light': 'Mode clair', 'theme.dark': 'Mode sombre', 'footer.explore': 'Explorer', 'footer.resources': 'Ressources', 'footer.legal': 'Mentions légales', 'footer.home': 'Accueil', 'footer.contact': 'Contact', 'footer.privacy': 'Confidentialité', 'footer.terms': 'Conditions' },
  de: { 'nav.pymes': 'Unternehmen', 'nav.learning': 'Lernen', 'nav.tools': 'Werkzeuge', 'nav.dashboard': 'Dashboard', 'nav.blog': 'Blog', 'nav.settings': 'Einstellungen', 'nav.profile': 'Mein Profil', 'nav.language': 'Sprache', 'settings.title': 'Einstellungen', 'settings.description': 'Passe an, wie Mentras auf der gesamten Website angezeigt wird.', 'settings.languageDetail': 'Lege die Sprache für Navigation und gemeinsame Ansichten fest.', 'settings.appearance': 'Darstellung', 'settings.appearanceDetail': 'Das ausgewählte Design gilt für die gesamte Website.', 'theme.light': 'Heller Modus', 'theme.dark': 'Dunkler Modus', 'footer.explore': 'Entdecken', 'footer.resources': 'Ressourcen', 'footer.legal': 'Rechtliches', 'footer.home': 'Startseite', 'footer.contact': 'Kontakt', 'footer.privacy': 'Datenschutz', 'footer.terms': 'Nutzungsbedingungen' },
  it: { 'nav.pymes': 'Imprese', 'nav.learning': 'Apprendimento', 'nav.tools': 'Strumenti', 'nav.dashboard': 'Dashboard', 'nav.blog': 'Blog', 'nav.settings': 'Impostazioni', 'nav.profile': 'Il mio profilo', 'nav.language': 'Lingua', 'settings.title': 'Impostazioni', 'settings.description': 'Personalizza come Mentras viene visualizzato in tutto il sito.', 'settings.languageDetail': 'Imposta la lingua usata nella navigazione e nelle schermate condivise.', 'settings.appearance': 'Aspetto', 'settings.appearanceDetail': 'Il tema selezionato si applica a tutto il sito.', 'theme.light': 'Modalità chiara', 'theme.dark': 'Modalità scura', 'footer.explore': 'Esplora', 'footer.resources': 'Risorse', 'footer.legal': 'Legale', 'footer.home': 'Home', 'footer.contact': 'Contatti', 'footer.privacy': 'Privacy', 'footer.terms': 'Termini' },
  nl: { 'nav.pymes': 'Bedrijven', 'nav.learning': 'Leren', 'nav.tools': 'Tools', 'nav.dashboard': 'Dashboard', 'nav.blog': 'Blog', 'nav.settings': 'Instellingen', 'nav.profile': 'Mijn profiel', 'nav.language': 'Taal', 'settings.title': 'Instellingen', 'settings.description': 'Pas aan hoe Mentras op de hele website wordt weergegeven.', 'settings.languageDetail': 'Stel de taal in voor navigatie en gedeelde schermen.', 'settings.appearance': 'Weergave', 'settings.appearanceDetail': 'Het gekozen thema geldt voor de hele website.', 'theme.light': 'Lichte modus', 'theme.dark': 'Donkere modus', 'footer.explore': 'Verkennen', 'footer.resources': 'Hulpmiddelen', 'footer.legal': 'Juridisch', 'footer.home': 'Home', 'footer.contact': 'Contact', 'footer.privacy': 'Privacy', 'footer.terms': 'Voorwaarden' },
}

export default languageNames
